# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
  use_frameworks!

workspace 'ProgamersExpert'

target 'ProgamersExpert' do

  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for ProgamersExpert
  pod 'SwiftLint'

  target 'ProgamersExpertTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProgamersExpertUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Common' do
    project '../Common/Common'
 
end

target 'Favorites' do
    project '../Favorites/Favorites'

end


target 'GameRow' do
    project '../GameRow/GameRow'

end

target 'Details' do
    project '../Details/Details'
end
