language: swift
osx_image: xcode13.1
xcode_project: ProgamersExpert/ProgamersExpert.xcodeproj 
xcode_scheme: ProgamersExpert
xcode_destination: platform=iOS Simulator,OS=14.0.1,name=iPhone 11 Pro

before_install:
  - gem install cocoapods-keys
