language: swift
osx_image: xcode13.1
xcode_project: ProgamersExpert/ProgamersExpert.xcodeproj 
xcode_scheme: ProgamersExpert
xcode_destination: platform=iOS Simulator,OS=14.0.1,name=iPhone 11 Pro

podfile: ProgamersExpert/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
- pod install --project-directory=ProgamersExpert
- git submodule update --init --recursive

script:
- set -o pipefail && xcodebuild -workspace ProgamersExpert/ProgamersExpert.xcworkspace -scheme ProgamersExpert -destination platform\=iOS\ Simulator,OS\=14.0.1,name\=iPhone\ 11\ Pro build test | xcpretty
